import type { Metadata } from "next";
import { Instrument_Sans, Azeret_Mono } from "next/font/google";
import "./globals.css";

/**
 * TYPE, AND WHY THESE TWO.
 *
 * Instrument Sans for prose and interface: a grotesk with slightly narrow
 * counters and real vertical tension, so headings hold at large sizes without
 * needing weight 900 to look deliberate. It is not the typeface every
 * infrastructure product currently ships, which matters — the house style of
 * this category (one very familiar geometric sans on near-black) reads as
 * credible and completely anonymous, and anonymous is the one thing a record
 * nobody has heard of cannot afford.
 *
 * Azeret Mono for identifiers, hashes, tokens and provenance: squared terminals
 * and a wide, engineered rhythm that makes an entry id look like a serial
 * number rather than a word. Mono here is semantic, not stylistic — everything
 * set in it is a thing you could copy, paste and verify.
 *
 * Both are variable and both are self-hosted by `next/font` at build time, so
 * there is no runtime request to a third party. That is not a performance nicety
 * on this product: the page can be opened by a partner's operator who is at that
 * moment deciding whether this domain deserves a credential, and a font call to
 * an ad-adjacent CDN is a bad answer to "what does this page talk to".
 */
const sans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const mono = Azeret_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Bridger",
  description: "A traced record between two builders' AI sessions.",
  // The page can display a partner's private integration record. It has no
  // business in a search index, and a link pasted anywhere should not preview
  // its contents.
  robots: { index: false, follow: false },
};

/**
 * ONE SCHEME, DECLARED UNCONDITIONALLY (S#285).
 *
 * This page is dark-only. `:root` pins `color-scheme: dark`, so a light theme
 * colour would only ever describe a surface that no longer exists — and a
 * browser on a light OS would paint its chrome cream over a near-black page.
 * The reason for the split is gone with the light palette; see the note above
 * the tokens in `globals.css`.
 */
export const viewport = {
  themeColor: "#07080a",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`}>
      <head>
        {/*
          The page's primary reader is an agent (Erik, S#279), and an agent that
          has fetched this HTML should not have to guess that a text rendering
          exists. `alternate` is the honest relation: /llms.txt is the same
          content in the encoding that reader would rather have, generated from
          the same source in `lib/site-content.ts`. /api/about is the machine
          record and is linked separately because it is a different KIND of
          thing -- generated by the running server, naming the commit that
          answered, and authoritative where the two disagree.
        */}
        <link rel="alternate" type="text/plain" href="/llms.txt" title="Bridger, as plain text" />
        <link rel="alternate" type="application/json" href="/api/about" title="What this server is" />
      </head>
      <body>{children}</body>
    </html>
  );
}
